[features]
seeds = false
skip-lint = false

[programs.devnet]
unitpay_settlement = "8dnCh8oSEranGo7BcS3mH7hrp81T364g7NUpVCyuok8h"

[programs.testnet]
unitpay_settlement = "8dnCh8oSEranGo7BcS3mH7hrp81T364g7NUpVCyuok8h"

[programs.localnet]
unitpay_settlement = "8dnCh8oSEranGo7BcS3mH7hrp81T364g7NUpVCyuok8h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "../../wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 
